[package]
name = "_01_"
version = "0.1.0"
authors = ["portfolio-y0711 <portfolio-y0711@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
